### ISSUE TITLE
How to load fontsource packages?

### ISSUE THREAD

**Issue by 8lall0** [wittyprogramming/tailwindcss-alpinejs-starter#1]
Hi,

i'm trying this starter and it works pretty well, but i have a problem on importing fontsource fonts.

I installed "Open Sans", and when i build, it prints
```
node_modules/@fontsource/open-sans/index.css: error: File could not be loaded: node_modules/@fontsource/open-sans/files/open-sans-latin-ext-400-normal.woff2
  52 │   src: url('./files/open-sans-latin-ext-400-normal.woff2') format('woff2'), url('./files/open-sans-all-400-...
```

Do you have any idea on how to deal with this? Maybe it's a esbuild related issue.

Thanks a lot.

**Comment by kzagoris** [comment]
Hi,

For CSS, the starter uses postcss; therefore, it is not an esbuild related issue.

In postcss.config.js it uses a postcss plugin for `postcss-import`: https://github.com/postcss/postcss-import

If you post a fork with the problem, I may help you more. However, from the error messages, it seems that you have not configured the URL correctly.

**Comment by 8lall0** [comment]
Yes, you were right. Closing the issue.

Thank you!
